[package]
name = "typst-master-template-hm"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Alexander <@TheBlackDragon4>"]
license = "MIT"
description = "Unofficial Master's thesis template for Munich University of Applied Sciences (Hochschule München)"
repository = "https://github.com/TheBlackDragon4/typst-master-template-hm.git"
keywords = ["HM", "München", "Munich", "Hochschule München", "Hochschule München für Angewandte Wissenschaften", "Munich University of Applied Sciences", "thesis", "master's thesis"]
categories = ["thesis"]
disciplines = ["computer-science"]
exclude = [".devcontainer/"]

[template]
path = "template"
entrypoint = "main.typ"

thumbnail = "main.png"
